source 'https://rubygems.org'

gem 'rails', '3.2.12'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'pg'
gem 'pg_search'


# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'less-rails'
  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  gem 'therubyracer'
  gem 'twitter-bootstrap-rails',  '~> 2.1.6'

  gem 'uglifier', '>= 1.0.3'
end

gem "rspec-rails", "~> 2.6", :group => [:test, :development]
gem "letter_opener", :group => :development
gem 'jquery-rails'
gem 'tire'
gem 'authlogic'
gem 'cancan'
gem 'kaminari'
gem 'pry'
gem 'pry-nav'
gem 'rabl'
gem 'delayed_job_active_record'
gem "daemons"
gem 'mini_magick'
gem 'carrierwave'
gem 'nokogiri'
gem 'simple_form'
gem 'capistrano'
gem 'rvm-capistrano'
gem 'newrelic_rpm', "~> 3.5.5.38"
gem 'ar_pg_array'
gem 'andand'
gem 'ancestry'
gem 'docsplit'
gem "ruby-readability", :require => 'readability'
gem 'yajl-ruby'
gem 'mailboxer'
gem 'settingslogic'
gem 'httparty'
gem 'activerecord-postgres-hstore'
gem 'public_activity'
gem 'airbrake'
gem 'fast-stemmer'

# cloud
gem 'alchemy-api-rb', require: 'alchemy_api'
gem 'rails-backbone'
gem 'inflection-js-rails'
gem 'spinjs-rails'

gem 'omniauth-mendeley'

group :test do
  gem 'test-unit'
  gem 'capybara', "=1.1.2"
  gem 'database_cleaner'
  gem 'selenium-webdriver'
  gem "factory_girl_rails"
  gem "shoulda"
  gem "timecop"
  gem "fakeweb"
  gem "libnotify"
  gem "guard-rspec"
  gem "guard-spork"
  gem 'spork'
  gem 'rb-inotify', '~> 0.8.8'
end

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
gem 'capistrano'

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'meta_request'
end
